version: '3.8'
services:
  pt-webui:
    build: .
    container_name: pt-webui
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - BASE_DIR=/downloads
    volumes:
      # 【重要】请根据不同宿主机，将冒号前面的路径改为真实的下载目录
      - ./downloads:/downloads
      # 探针透视眼：读取宿主机真实物理硬件数据
      - /proc:/host_proc:ro
